name: todoapp-stack
x-build-configs:
  backend: &backend-build
    context: ../backend
    dockerfile: Dockerfile
  frontend: &frontend-build
    context: ../frontend
    dockerfile: Dockerfile

services:
  backend-1:
    build: *backend-build
    image: todoappstack-backend:0.1
    container_name: backend-1
    expose:
    - "8080"
  backend-2:
    image: todoappstack-backend:0.1
    container_name: backend-2
    expose:
    - "8080"
  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
  frontend:
    build: *frontend-build
    image: todoappstack-frontend:0.1
    container_name: frontend
    ports:
      - "80:3000"
  database:
    image: mongo:4
    container_name: database
    env_file:
      - ../database/.env
    ports:
      - "27017:27017"
    volumes:
      - ../database/mongo-db:/data/db